name:                hs-opentelemetry-instrumentation-yesod
version:             0.1.0.0
github:              "iand675/hs-opentelemetry"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry-instrumentation-yesod#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- microlens
- yesod-core
- hs-opentelemetry-api
- hs-opentelemetry-instrumentation-wai
- unliftio
- text
- template-haskell
- wai

library:
  ghc-options: -Wall
  source-dirs: src

tests:
  hs-opentelemetry-instrumentation-yesod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-yesod
