name: yesod-minimal

dependencies:
# minimal example dependencies
- base
- bytestring
- conduit
- yesod-core
- yesod-form
- http-client
- http-types
- wai
- warp
- text
- vault
# database
- yesod-persistent
- monad-logger
- persistent
- persistent-postgresql
- persistent-qq
- resource-pool
# convenience
- microlens
# opentelemetry dependencies
- hs-opentelemetry-sdk
- hs-opentelemetry-exporter-handle
- hs-opentelemetry-instrumentation-wai
- hs-opentelemetry-instrumentation-yesod
- hs-opentelemetry-instrumentation-http-client
- hs-opentelemetry-instrumentation-persistent
- hs-opentelemetry-propagators-w3c
- hs-opentelemetry-exporter-otlp

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    dependencies:
    - yesod-minimal

library:
    source-dirs: src
