name: yesod-minimal

dependencies:
# minimal example dependencies
- base
- bytestring
- yesod-core
- yesod-form
- http-client
- http-types
- wai
- warp
- text
# convenience
- microlens
# opentelemetry dependencies
- otel-sdk
- otel-exporter-handle
- otel-instrumentation-wai
- otel-instrumentation-yesod
- otel-instrumentation-http-client
- otel-propagators-w3c

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    dependencies:
    - yesod-minimal

library:
    source-dirs: src
