name: yesod-minimal

dependencies:
# minimal example dependencies
- base
- bytestring
- conduit
- yesod-core
- yesod-form
- http-client
- http-types
- wai
- warp
- text
- vault
# database
- yesod-persistent
- monad-logger
- persistent
- persistent-postgresql
- persistent-qq
- resource-pool
# convenience
- microlens
# opentelemetry dependencies
- otel-sdk
- otel-exporter-handle
- otel-instrumentation-wai
- otel-instrumentation-yesod
- otel-instrumentation-http-client
- otel-instrumentation-persistent
- otel-propagators-w3c
- otel-exporter-otlp
- otel-exporter-honeycomb

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    dependencies:
    - yesod-minimal

library:
    source-dirs: src
