name:                hs-opentelemetry-sdk
version:             0.1.0.0
github:              "iand675/hs-opentelemetry"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry-sdk#readme>

default-extensions:
- PackageImports

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
# These are "distribution" packages
- hs-opentelemetry-api
- hs-opentelemetry-propagators-w3c
- hs-opentelemetry-exporter-otlp


- async
- vector
- stm
- unagi-chan
- unordered-containers
- vector-builder
- http-types
- network-bsd
- unix
# todo get rid of this when enough of the ecosystem has upgraded
- random
- mwc-random
- random-bytestring

library:
  ghc-options: -Wall
  source-dirs: src
  other-modules:
  - Paths_hs_opentelemetry_sdk

tests:
  hs-opentelemetry-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-opentelemetry-sdk
