name:                hs-opentelemetry-api
version:             0.1.0.0
github:              "iand675/hs-opentelemetry"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            OpenTelemetry API. Intended for use by libraries for direct instrumentation or wrapper packages.
category:            OpenTelemetry, Telemetry, Monitoring, Observability, Metrics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry-api#readme>

default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- text
- vault
- containers
- hashable
- thread-utils-context
- unordered-containers
- binary
- random
- mwc-random
- vector
- clock
- memory
- mtl
- http-types
- attoparsec
- template-haskell
- charset
- ghc-prim
- unliftio-core
- microlens
- unix
# todo get rid of this when enough of the ecosystem has upgraded
- random-bytestring
- vector-builder
- network-bsd

library:
  source-dirs: src
  ghc-options: -Wall
  other-modules:
  - OpenTelemetry.Context.Types
  - OpenTelemetry.Internal.Trace.Id
  - OpenTelemetry.Internal.Trace.Types
  - OpenTelemetry.Trace.Core
  # TODO
  - OpenTelemetry.Propagators.B3
  - OpenTelemetry.Propagators.Jaeger

tests:
  hs-opentelemetry-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-opentelemetry-api
    - vector
    - vector-builder
