name:                otel-api
version:             0.1.0.0
github:              "iand675/otel-api"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/otel-api#readme>

default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- async
- binary
- bytestring
- text
- unordered-containers
- vault
- thread-utils-context
- random
- mwc-random
- vector
- clock
- memory
- mtl
- http-types
- attoparsec
- template-haskell
- hashable
- charset
- ghc-prim
- unliftio-core
- microlens
- unix
# todo get rid of this when enough of the ecosystem has upgraded
- random-bytestring

library:
  source-dirs: src
  ghc-options: -Wall -Werror
  other-modules:
  - OpenTelemetry.Internal
  - OpenTelemetry.Context.Types
  - OpenTelemetry.Internal.Trace.Types

tests:
  otel-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - otel-api
