on:
  push:
  pull_request:
jobs:
  ghc-9_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}
      - run: stack build --only-dependencies
      - run: stack build
      - run: stack test
  ghc-9_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-9.2-${{ hashFiles('stack-ghc-9.2.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}-9.2
      - run: stack --stack-yaml stack-ghc-9.2.yaml build --only-dependencies
      - run: stack --stack-yaml stack-ghc-9.2.yaml build
      - run: stack --stack-yaml stack-ghc-9.2.yaml test

